name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    ## This is used to not re-run the build if only thoses files have changed
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18"
          cache: "yarn"
      - name: Configure Node
        run: |
          yarn set version stable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
        
  MacOs:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18"
          cache: "yarn"
      - name: Configure Node
        run: |
          # npm v9 doesn't allow custom config parameters (i.e. node_gyp) anymode, so we have to downgrade it to v8
          npm install -g npm@8  
          npm install -g node-gyp@latest
          npm config set node_gyp $(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js
          yarn set version stable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Tests
        run: yarn test

  Windows:
    runs-on: windows-2019
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18"
          cache: "yarn"
      - name: Configure Node
        shell: powershell
        run: |
          # npm v9 doesn't allow custom config parameters (i.e. node_gyp) anymode, so we have to downgrade it to v8
          npm install -g npm@8  
          npm install -g node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
          yarn set version stable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Tests
        run: yarn run test
